### ISSUE TITLE
Conflicting with Excalidraw plugin embeds

### ISSUE THREAD

**Issue by lucmos** [sissilab/obsidian-image-toolkit#102]
Hello, 

Unfortunately, the [excalidraw plugin](https://github.com/zsviczian/obsidian-excalidraw-plugin) and this plugin conflict.

It is not possible to open an embedded excalidraw canvas when this plugin is active:
![image](https://github.com/sissilab/obsidian-image-toolkit/assets/11019190/74b1511e-70d3-4eb1-b9a5-987aa1aeb8e1)

Is there any way to work around this?

Thanks!

**Comment by itsonlyjames** [comment]
+1. Might look into fixing this myself as it completely impedes on the excalidraw workflow

**Comment by itsonlyjames** [comment]
```
private isImageElement = (imgEl: HTMLImageElement): boolean => {
        return (
            imgEl &&
            'IMG' === imgEl.tagName &&
            imgEl.className !==
                'excalidraw-svg excalidraw-embedded-img excalidraw-canvas-immersive'
        )
    }
```
![image](https://github.com/sissilab/obsidian-image-toolkit/assets/6904599/03add134-625f-4c13-bfd3-9ba8e2f32ec5)

That fixes the issue and excalidraw now reverts to requiring a double click to open, but I wonder actually if keeping the svg image capabilities are worthwhile, for example you can zoom infinitely for clarity because it's an SVG. It just needs some tweaks to make it work correctly (render in the gallery view, and open at a larger real size).

It isn't the most sound piece of code as the class could change and I've only tested a few things, but I'm definitely thinking about opening a PR and seeing if @sissilab can help us out 👍

**Comment by sissilab** [comment]
@lucmos It seems there is not any conflict now and I'll close this thread now. Please feel free to give feedback if you still got any trouble.

**Comment by itsonlyjames** [comment]
Good spot @sissilab. Confirmed it's working now on the latest Excalidraw version 🎉

I _think_ it was fixed in [this](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/2.2.5) version, but eh, can't be bothered figuring out for sure!

**Comment by sissilab** [comment]
> Good spot @sissilab. Confirmed it's working now on the latest Excalidraw version 🎉
> 
> I _think_ it was fixed in [this](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/2.2.5) version, but eh, can't be bothered figuring out for sure!

Thank you for providing this clue. I'll keep an key on it if encountering any conflict again.
